export const references = [
  { slug: "vila-b-rik--ilina", image: "/images/references/ref-01.jpg", title: "Vila Bôrik", location: "Žilina", year: "2022", type: "Na kľúč" },
  { slug: "modern-bungalov-tren-n", image: "/images/references/ref-03.jpg", title: "Moderný bungalov", location: "Trenčín", year: "2023", type: "Na kľúč" },
  { slug: "rodinn-dom-bratislava", image: "/images/references/ref-05.jpeg", title: "Rodinný dom", location: "Bratislava", year: "2024", type: "Na kľúč" },
  { slug: "podkrovn-dom--ilina-zamarovce", image: "/images/references/ref-14.jpg", title: "Podkrovný dom", location: "Žilina - Zamarovce", year: "2023", type: "Na kľúč" },
  { slug: "poschodov-dom-brno", image: "/images/references/ref-15.jpg", title: "Poschodový dom", location: "Brno, ČR", year: "2024", type: "Na kľúč" },
  { slug: "dom-v-lehote--ilinsk-lehota", image: "/images/references/ref-18.jpg", title: "Dom v Lehote", location: "Žilinská Lehota", year: "2023", type: "Na kľúč" },
  { slug: "rodinn-dom-v-kopci-terchov", image: "/images/references/ref-20.jpg", title: "Rodinný dom v kopci", location: "Terchová", year: "2024", type: "Na kľúč" },
  { slug: "dom-v-prieluke-martin", image: "/images/references/ref-23.jpg", title: "Dom v prieluke", location: "Martin", year: "2022", type: "Na kľúč" },
  { slug: "poschodov-2301-pova-sk-bystrica", image: "/images/references/ref-24.jpg", title: "Poschodový 2301", location: "Považská Bystrica", year: "2023", type: "Poschodový" },
  { slug: "modern-rodinn-dom-trnava", image: "/images/references/ref-25.jpg", title: "Moderný rodinný dom", location: "Trnava", year: "2024", type: "Na kľúč" },
  { slug: "bungalov-2008-nitra", image: "/images/references/ref-29.jpg", title: "Bungalov 2008", location: "Nitra", year: "2021", type: "Bungalov" },
  { slug: "dom-pod-tatrami-poprad", image: "/images/references/ref-30.jpg", title: "Dom pod Tatrami", location: "Poprad", year: "2022", type: "Na kľúč" },
  { slug: "poschodov-2202--ilina", image: "/images/references/ref-34.jpg", title: "Poschodový 2202", location: "Žilina", year: "2022", type: "Poschodový" },
  { slug: "rodinn-dom-prievidza", image: "/images/references/ref-35.jpg", title: "Rodinný dom", location: "Prievidza", year: "2021", type: "Na kľúč" },
  { slug: "n-zkoenergetick-dom-bansk-bystrica", image: "/images/references/ref-38.jpg", title: "Nízkoenergetický dom", location: "Banská Bystrica", year: "2023", type: "Na kľúč" },
  { slug: "modern-bungalov-pie-any", image: "/images/references/ref-40.jpg", title: "Moderný bungalov", location: "Piešťany", year: "2024", type: "Bungalov" },
  { slug: "rodinn-dom-ru-omberok", image: "/images/references/ref-42.jpg", title: "Rodinný dom", location: "Ružomberok", year: "2020", type: "Na kľúč" },
  { slug: "pas-vny-dom-zvolen", image: "/images/references/ref-45.jpg", title: "Pasívny dom", location: "Zvolen", year: "2023", type: "Na kľúč" },
  { slug: "dvojpodla-n-dom-tren-n", image: "/images/references/ref-46.jpg", title: "Dvojpodlažný dom", location: "Trenčín", year: "2024", type: "Poschodový" },
  { slug: "rodinn-dom-dubnica-nad-v-hom", image: "/images/references/ref-50.jpg", title: "Rodinný dom", location: "Dubnica nad Váhom", year: "2022", type: "Na kľúč" },
  { slug: "hrub-stavba-byt-a", image: "/images/references/ref-04.jpg", title: "Hrubá stavba", location: "Bytča", year: "2021", type: "Hrubá stavba" },
  { slug: "kompaktn-bungalov-kysuck-nov-mesto", image: "/images/references/ref-06.jpg", title: "Kompaktný bungalov", location: "Kysucké Nové Mesto", year: "2020", type: "Bungalov" },
  { slug: "dom-na-zkom-pozemku--adca", image: "/images/references/ref-08.jpg", title: "Dom na úzkom pozemku", location: "Čadca", year: "2023", type: "Na kľúč" },
  { slug: "dvojgenera-n-dom-liptovsk-mikul", image: "/images/references/ref-10.jpg", title: "Dvojgeneračný dom", location: "Liptovský Mikuláš", year: "2022", type: "Poschodový" },
  { slug: "bungalov-klasik-doln-kub-n", image: "/images/references/ref-11.jpg", title: "Bungalov klasik", location: "Dolný Kubín", year: "2019", type: "Bungalov" },
  { slug: "rodinn-dom-n-mestovo", image: "/images/references/ref-12.jpg", title: "Rodinný dom", location: "Námestovo", year: "2020", type: "Hrubá stavba" },
  { slug: "dom-so-sedlovou-strechou-topo-any", image: "/images/references/ref-26.jpg", title: "Dom so sedlovou strechou", location: "Topoľčany", year: "2021", type: "Na kľúč" },
  { slug: "modern-poschodov--levice", image: "/images/references/ref-28.jpg", title: "Moderný poschodový", location: "Levice", year: "2023", type: "Poschodový" },
  { slug: "kompaktn-dom-nov-z-mky", image: "/images/references/ref-32.jpg", title: "Kompaktný dom", location: "Nové Zámky", year: "2024", type: "Na kľúč" },
  { slug: "hrub-stavba-kom-rno", image: "/images/references/ref-37.jpg", title: "Hrubá stavba", location: "Komárno", year: "2022", type: "Hrubá stavba" },
  { slug: "rodinn-dom-galanta", image: "/images/references/ref-39.jpg", title: "Rodinný dom", location: "Galanta", year: "2021", type: "Na kľúč" },
  { slug: "bungalov-premium--a-a", image: "/images/references/ref-41.jpg", title: "Bungalov premium", location: "Šaľa", year: "2023", type: "Bungalov" },
  { slug: "dom-s-gar-ou-sere", image: "/images/references/ref-43.jpg", title: "Dom s garážou", location: "Sereď", year: "2020", type: "Poschodový" },
  { slug: "energeticky-sporn--humenn", image: "/images/references/ref-44.jpg", title: "Energeticky úsporný", location: "Humenné", year: "2024", type: "Na kľúč" },
  { slug: "rodinn-dom-michalovce", image: "/images/references/ref-47.jpg", title: "Rodinný dom", location: "Michalovce", year: "2022", type: "Na kľúč" },
  { slug: "bungalov-modern-ko-ice", image: "/images/references/ref-48.jpg", title: "Bungalov modern", location: "Košice", year: "2023", type: "Bungalov" },
  { slug: "poschodov-elegance-pre-ov", image: "/images/references/ref-49.jpg", title: "Poschodový elegance", location: "Prešov", year: "2024", type: "Poschodový" },
];

export const referenceCategories = ["Všetky", "Na kľúč", "Bungalov", "Poschodový", "Hrubá stavba"];
